### ISSUE TITLE
Optional hashing when creating and querying

### ISSUE THREAD

**Issue by rennex** [Freaky/gcstool#1]
Currently `gcstool create` expects sha1 hashes in the input file, and `gcstool query` expects raw strings that it will hash with sha1. It would be good to make hashing optional in both cases, so I could create a set with raw inputs and query it with hashes. And a selectable hashing algorithm would be a plus.

**Comment by Freaky** [comment]
It doesn't really care what the inputs are, so long as each line starts with 16 bytes of hex, but yeah, it does need to be made more flexible and that is on the todo list.

Mainly a matter of picking an appropriate crate.  Thinking either [crypto-hash](https://crates.io/crates/crypto-hash) or maybe [crypto-hashes](https://crates.io/crates/crypto-hashes) for a wider range of options (and more dependencies).

**Comment by Freaky** [comment]
New global flag added:

    OPTIONS:
        -H, --hash <hash>    Hash function [default: sha1]  [possible values: hex, sha1]

Will close this once it's a bit less limited.
